apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: observability
spec:
  releaseName: jaeger-operator
  chart:
    spec:
      chart: jaeger-operator
      version: '2.57.0'
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: observability
  interval: 120m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger-operator/values.yaml
  values:
    certs:
      issuer:
        create: true
        name: ""
      certificate:
        create: true
        namespace: "observability"
        secretName: ""
        issuerKind: Issuer

    webhooks:
      mutatingWebhook:
        create: true
      validatingWebhook:
        create: true
      port: 9443
      service:
        annotations: {}
        create: true

    jaeger:
      create: false

    rbac:
      create: true
      pspEnabled: false
      clusterRole: true

    service:
      type: ClusterIP

    serviceAccount:
      create: true

    replicaCount: 1

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 50Mi

    metricsPort: 8383